# Generated by Django 5.2.4 on 2025-08-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
