# Generated by Django 5.2.4 on 2025-08-18 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml_models', '0001_initial'),
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='modeltraininglog',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='ml_models.mlmodel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='modeltraininglog',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Started By'),
        ),
        migrations.AddField(
            model_name='predictionaccuracy',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy_metrics', to='ml_models.mlmodel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='predictionaccuracy',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_models.mlmodel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='stockprediction',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='stocks.stock', verbose_name='Stock'),
        ),
        migrations.AlterUniqueTogether(
            name='stockprediction',
            unique_together={('model', 'stock', 'prediction_date')},
        ),
    ]
